language: php

sudo: false

install:
  - pear install XML_Parser-1.3.6
  - pear install package.xml

script:
  - phpunit
  - composer validate

branches:
  only:
  - master

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
